const path = require('path');
const fs = require('fs');

// __dirname is the path to the folder where this file (compile.js) exists.
// Get the path and filename to Inbox.sol.
const lotteryPath = path.resolve(__dirname, 'contracts', 'Lottery.sol');
const source = fs.readFileSync(lotteryPath, 'utf8');

// Get Solidity Compiler
const solc = require('solc');
// 1: number of contracts to compile
// Log what the compiler is doing.
//console.log(solc.compile(source, 1));
//Export the compiled contracts.
//Instead of exporting all the blocks generated by compiler
//only outout contracts' Inbox part including Bytecode and ABI.
module.exports = solc.compile(source, 1).contracts[':Lottery'];
